/*
 * Copyright (c) 2022-2025 Tim Savage.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.winterhavenmc.lodestar.plugin.util;

/**
 * Enum with entries for all player messages in language configuration files
 */
public enum MessageId
{
	COMMAND_SUCCESS_BIND,
	COMMAND_SUCCESS_DELETE,
	COMMAND_SUCCESS_DESTROY,
	COMMAND_SUCCESS_GIVE_OTHER,
	COMMAND_SUCCESS_GIVE_SELF,
	COMMAND_SUCCESS_GIVE_TARGET,
	COMMAND_SUCCESS_RELOAD,
	COMMAND_SUCCESS_SET,

	COMMAND_SUCCESS_HELP_BIND,
	COMMAND_SUCCESS_HELP_DELETE,
	COMMAND_SUCCESS_HELP_DESTROY,
	COMMAND_SUCCESS_HELP_GIVE,
	COMMAND_SUCCESS_HELP_HELP,
	COMMAND_SUCCESS_HELP_LIST,
	COMMAND_SUCCESS_HELP_RELOAD,
	COMMAND_SUCCESS_HELP_SET,
	COMMAND_SUCCESS_HELP_STATUS,
	COMMAND_SUCCESS_HELP_TELEPORT,
	COMMAND_SUCCESS_HELP_USAGE_HEADER,

	COMMAND_WARN_SET_NUMERIC_PREFIX,

	COMMAND_FAIL_ARGS_COUNT_OVER,
	COMMAND_FAIL_ARGS_COUNT_UNDER,
	COMMAND_FAIL_CONSOLE,
	COMMAND_FAIL_DELETE_RESERVED,
	COMMAND_FAIL_GIVE_INVENTORY_FULL,
	COMMAND_FAIL_INVALID_COMMAND,
	COMMAND_FAIL_INVALID_DESTINATION,
	COMMAND_FAIL_INVALID_MATERIAL,
	COMMAND_FAIL_INVALID_ITEM,
	COMMAND_FAIL_PLAYER_NOT_FOUND,
	COMMAND_FAIL_SET_RESERVED,
	COMMAND_FAIL_SET_REASON,
	COMMAND_FAIL_PLAYER_NOT_ONLINE,
	COMMAND_FAIL_HELP_INVALID_COMMAND,

	COMMAND_FAIL_BIND_PERMISSION_DENIED,
	COMMAND_FAIL_DELETE_PERMISSION_DENIED,
	COMMAND_FAIL_DESTROY_PERMISSION_DENIED,
	COMMAND_FAIL_GIVE_PERMISSION_DENIED,
	COMMAND_FAIL_HELP_PERMISSION_DENIED,
	COMMAND_FAIL_LIST_PERMISSION_DENIED,
	COMMAND_FAIL_OVERWRITE_PERMISSION_DENIED,
	COMMAND_FAIL_RELOAD_PERMISSION_DENIED,
	COMMAND_FAIL_SET_PERMISSION_DENIED,
	COMMAND_FAIL_STATUS_PERMISSION_DENIED,
	COMMAND_FAIL_TELEPORT_PERMISSION_DENIED,

	COMMAND_STATUS_HEADER,
	COMMAND_STATUS_PLUGIN_VERSION,
	COMMAND_STATUS_LANGUAGE,
	COMMAND_STATUS_LOCALE,
	COMMAND_STATUS_TIMEZONE,
	COMMAND_STATUS_DEFAULT_MATERIAL,
	COMMAND_STATUS_MINIMUM_DISTANCE,
	COMMAND_STATUS_TELEPORT_WARMUP,
	COMMAND_STATUS_TELEPORT_COOLDOWN,
	COMMAND_STATUS_SHIFT_CLICK,
	COMMAND_STATUS_CANCEL_ON_DAMAGE,
	COMMAND_STATUS_CANCEL_ON_MOVEMENT,
	COMMAND_STATUS_CANCEL_ON_INTERACTION,
	COMMAND_STATUS_INVENTORY_REMOVAL,
	COMMAND_STATUS_ALLOW_IN_RECIPES,
	COMMAND_STATUS_DISPLAY_LIGHTNING,
	COMMAND_STATUS_ENABLED_WORLDS,
	COMMAND_STATUS_FOOTER,
	COMMAND_STATUS_FROM_NETHER,
	COMMAND_STATUS_FROM_END,

	COMMAND_LIST_HEADER,
	COMMAND_LIST_FOOTER,
	COMMAND_LIST_ITEM_VALID,
	COMMAND_LIST_ITEM_INVALID,
	COMMAND_LIST_EMPTY,

	EVENT_ITEM_USE_LOG,
	EVENT_ITEM_USE_PERMISSION_DENIED,

	EVENT_TELEPORT_CANCELLED_DAMAGE,
	EVENT_TELEPORT_CANCELLED_INTERACTION,
	EVENT_TELEPORT_CANCELLED_MOVEMENT,
	EVENT_TELEPORT_CANCELLED_NO_ITEM,

	EVENT_TELEPORT_FAIL_INVALID_DESTINATION,
	EVENT_TELEPORT_FAIL_NO_BEDSPAWN,
	EVENT_TELEPORT_FAIL_PROXIMITY,
	EVENT_TELEPORT_FAIL_SHIFT_CLICK,
	EVENT_TELEPORT_FAIL_WORLD_DISABLED,

	EVENT_TELEPORT_SUCCESS_DESTINATION,
	EVENT_TELEPORT_SUCCESS_SPAWN,

	EVENT_TELEPORT_COOLDOWN,
	EVENT_TELEPORT_WARMUP_DESTINATION,
	EVENT_TELEPORT_WARMUP_SPAWN,
}
