name: 'LodeStar'
main: com.winterhavenmc.lodestar.plugin.PluginMain
author: '${project.author}'
version: '${project.version}'
api-version: 1.18
softdepend: [ Iris, Multiverse-Core, My_Worlds ]

commands:
  lodestar:
    description: Use /lodestar help [command] for help.
    usage: /lodestar [command]

permissions:
  lodestar.use:
    description: 'Allows the use of a lodestar.'
    default: true

  lodestar.list:
    description: 'List all LodeStar locations.'
    default: op

  lodestar.help:
    description: 'Display help for LodeStar commands.'
    default: op

  lodestar.command:
    description: 'Allow use of LodeStar command.'
    default: op

  lodestar.status:
    description: 'Allows display of config settings.'
    default: op

  lodestar.reload:
    description: 'Allows reloading the config file.'
    default: op

  lodestar.give:
    description: 'Allows giving LodeStar items to players.'
    default: op

  lodestar.destroy:
    description: 'Allows destroying LodeStar items in hand.'
    default: op

  lodestar.set:
    description: 'Allows setting a LodeStar location.'
    default: op

  lodestar.teleport:
    description: 'Allows teleporting to a LodeStar location.'
    default: op

  lodestar.set.overwrite:
    description: 'Allows overwriting a LodeStar location.'
    default: op

  lodestar.bind:
    description: 'Allows binding a LodeStar location to a LodeStar item.'
    default: op

  lodestar.delete:
    description: 'Allows deleting a LodeStar location.'
    default: op

  lodestar.admin:
    description: 'Allows all admin commands.'
    default: op
    children:
      lodestar.bind: true
      lodestar.give: true
      lodestar.delete: true
      lodestar.destroy: true
      lodestar.help: true
      lodestar.list: true
      lodestar.reload: true
      lodestar.set: true
      lodestar.set.overwrite: true
      lodestar.status: true
      lodestar.teleport: true

  lodestar.default-override:
    description: 'Allows overriding default-item-only setting.'
    default: op
